// src/core/emoji-data.js — 表情符号数据库
// 字段：c=字符, n=中文名, k=关键词（空格分隔，便于搜索匹配）

const EMOJI_CATEGORIES = [
  {
    id: 'smileys', name: '笑脸表情', icon: '😀',
    emojis: [
      { c: '😀', n: '笑脸', k: '开心 微笑 happy 笑' },
      { c: '😃', n: '大笑', k: '开心 大笑 哈哈' },
      { c: '😄', n: '开心', k: '开心 笑 happy' },
      { c: '😁', n: '咧嘴笑', k: '笑 露齿 happy' },
      { c: '😆', n: '眯眼笑', k: '笑 嘿嘿 happy' },
      { c: '😅', n: '苦笑', k: '尴尬 汗 苦笑' },
      { c: '🤣', n: '笑倒', k: '笑倒 哈哈 rofl 捧腹' },
      { c: '😂', n: '笑哭', k: '笑哭 哈哈 流泪 joy' },
      { c: '🙂', n: '微笑', k: '微笑 smile' },
      { c: '🙃', n: '倒脸', k: '倒立 反转 颠倒' },
      { c: '😉', n: '眨眼', k: '眨眼 wink 调皮' },
      { c: '😊', n: '害羞笑', k: '害羞 开心 脸红 blush' },
      { c: '😇', n: '天使', k: '天使 天真 halo 善良' },
      { c: '🥰', n: '被爱', k: '爱 幸福 心 heart 恋爱' },
      { c: '😍', n: '花痴', k: '爱 心 喜欢 花痴' },
      { c: '🤩', n: '好崇拜', k: '崇拜 星星眼 starstruck' },
      { c: '😘', n: '飞吻', k: '亲亲 吻 kiss 爱' },
      { c: '😚', n: '闭眼吻', k: '亲吻 kiss 闭眼' },
      { c: '😋', n: '好吃', k: '美味 好吃 舌头 yummy' },
      { c: '😛', n: '吐舌', k: '吐舌 调皮 tongue' },
      { c: '😜', n: '眨眼吐舌', k: '吐舌 眨眼 调皮 wink' },
      { c: '🤪', n: '鬼脸', k: '鬼脸 疯 zany 调皮' },
      { c: '😝', n: '闭眼吐舌', k: '吐舌 闭眼 调皮' },
      { c: '🤑', n: '财迷', k: '钱 财迷 money 富有' },
      { c: '🤓', n: '书呆', k: '书呆 眼镜 nerdy 学霸' },
      { c: '🧐', n: '考究', k: '检查 眼镜 考究' },
      { c: '🤔', n: '思考', k: '思考 想 think 疑惑' },
      { c: '🤭', n: '捂嘴', k: '捂嘴 偷笑 羞 cover' },
      { c: '🤫', n: '嘘', k: '嘘 安静 别说话 shush' },
      { c: '🤥', n: '撒谎', k: '撒谎 鼻子 lie' },
      { c: '😐', n: '面无表情', k: '无表情 平静 neutral' },
      { c: '😑', n: '无语', k: '无语 面无表情' },
      { c: '😶', n: '闭嘴', k: '闭嘴 无言 silent 沉默' },
      { c: '😏', n: '得意', k: '得意 暗笑 smirk' },
      { c: '😒', n: '不屑', k: '不屑 无趣 unamused 哼' },
      { c: '🙄', n: '翻白眼', k: '翻白眼 无语 roll 嫌弃' },
      { c: '😬', n: '尴尬', k: '尴尬 龇牙 grimace' },
      { c: '😮‍💨', n: '叹气', k: '叹气 呼气 无奈 sigh' },
      { c: '😌', n: '宽慰', k: '宽慰 放松 relieved 舒服' },
      { c: '😔', n: '沮丧', k: '沮丧 难过 sad 沉思' },
      { c: '😪', n: '困倦', k: '困 睡觉 sleepy 累' },
      { c: '🤤', n: '流口水', k: '流口水 馋 drool 想吃' },
      { c: '😴', n: '睡觉', k: '睡觉 睡着 zzz sleep' },
      { c: '😷', n: '生病', k: '生病 口罩 感冒 sick mask' },
      { c: '🤒', n: '发烧', k: '发烧 体温计 生病 thermometer' },
      { c: '🤕', n: '受伤', k: '受伤 绷带 hurt bandage' },
      { c: '🤢', n: '恶心', k: '恶心 反胃 nauseated 难受' },
      { c: '🤮', n: '呕吐', k: '呕吐 吐 vomit 恶心' },
      { c: '🥵', n: '热', k: '热 发烧 hot 冒汗' },
      { c: '🥶', n: '冷', k: '冷 冻 freezing 寒冷' },
      { c: '🥴', n: '眩晕', k: '晕 醉 woozy 迷糊' },
      { c: '😵', n: '晕倒', k: '晕倒 dizzy 昏' },
      { c: '🤯', n: '脑炸', k: '震惊 爆炸 mind blown 崩溃' },
      { c: '🤠', n: '牛仔', k: '牛仔 帽子 cowboy' },
      { c: '🥳', n: '庆祝', k: '庆祝 派对 party 生日' },
      { c: '😎', n: '酷', k: '酷 墨镜 cool 帅' },
      { c: '😕', n: '困惑', k: '困惑 confused 疑惑' },
      { c: '😟', n: '担心', k: '担心 worried 忧虑' },
      { c: '🙁', n: '皱眉', k: '皱眉 不开心 frown' },
      { c: '☹️', n: '难过', k: '难过 sad 悲伤' },
      { c: '😮', n: '惊讶', k: '惊讶 张嘴 surprised 哇' },
      { c: '😲', n: '吃惊', k: '吃惊 震惊 astonished 哇' },
      { c: '😳', n: '脸红', k: '脸红 害羞 flushed 尴尬' },
      { c: '🥺', n: '恳求', k: '恳求 求你 puppy eyes 可怜' },
      { c: '😨', n: '害怕', k: '害怕 fear 恐惧' },
      { c: '😰', n: '焦虑', k: '焦虑 汗 anxious 紧张' },
      { c: '😥', n: '失望', k: '失望 sad 汗 难过' },
      { c: '😢', n: '哭', k: '哭 哭泣 cry 泪 tear' },
      { c: '😭', n: '大哭', k: '大哭 嚎啕 sob 哭 流泪' },
      { c: '😱', n: '吓哭', k: '吓哭 惊恐 scream 恐惧' },
      { c: '😖', n: '困扰', k: '困扰 confounded 烦躁' },
      { c: '😣', n: '忍耐', k: '忍耐 persevere 痛苦' },
      { c: '😞', n: '失望', k: '失望 sad 沮丧 disappointed' },
      { c: '😓', n: '汗', k: '汗 苦笑 疲惫 sweat' },
      { c: '😩', n: '疲惫', k: '疲惫 累 weary 唉' },
      { c: '😫', n: '累', k: '累 疲惫 tired 唉' },
      { c: '🥱', n: '打哈欠', k: '哈欠 困 yawn 无聊' },
      { c: '😤', n: '哼', k: '哼 怒 huff 哼唧' },
      { c: '😡', n: '愤怒', k: '愤怒 生气 rage pout 怒' },
      { c: '😠', n: '生气', k: '生气 angry 怒' },
      { c: '🤬', n: '爆粗', k: '爆粗 骂 cursing 愤怒' },
      { c: '😈', n: '恶魔笑', k: '恶魔 笑 devil 角 坏' },
      { c: '👿', n: '小恶魔', k: '恶魔 devil 角' },
      { c: '💀', n: '骷髅', k: '骷髅 死 skull 死亡' },
      { c: '☠️', n: '骷髅叉', k: '骷髅 危险 poison 死' },
      { c: '💩', n: '大便', k: '大便 屎 poop 嗯嗯' },
      { c: '🤡', n: '小丑', k: '小丑 clown 丑' },
      { c: '👹', n: '妖怪', k: '妖怪 ogre 鬼' },
      { c: '👻', n: '幽灵', k: '幽灵 鬼 ghost 万圣节' },
      { c: '👽', n: '外星人', k: '外星人 alien 外星' },
      { c: '👾', n: '怪物', k: '怪物 alien 怪 游戏' },
      { c: '🤖', n: '机器人', k: '机器人 robot ai 智能' },
      { c: '😺', n: '猫笑', k: '猫 笑 happy cat' },
      { c: '😸', n: '猫眯眼笑', k: '猫 笑 grin cat' },
      { c: '😹', n: '猫笑哭', k: '猫 笑泪 joy cat' },
      { c: '😻', n: '猫花痴', k: '猫 爱 heart cat' },
      { c: '🙀', n: '猫惊', k: '猫 惊吓 scream cat' },
      { c: '😿', n: '猫哭', k: '猫 哭 cry cat' },
      { c: '😾', n: '猫怒', k: '猫 怒 pout cat' }
    ]
  },
  {
    id: 'gestures', name: '手势人物', icon: '👋',
    emojis: [
      { c: '👋', n: '挥手', k: '挥手 再见 hi wave 你好' },
      { c: '🤚', n: '手背', k: '手背 stop raised 停' },
      { c: '🖐️', n: '五指', k: '五指 hand 手' },
      { c: '✋', n: '停', k: '停 stop hand 举手' },
      { c: '🖖', n: '瓦肯礼', k: '瓦肯 vulcan 你好' },
      { c: '👌', n: 'OK', k: 'ok 好 手势 没问题' },
      { c: '🤌', n: '捏手指', k: '捏手指 意大利 pinched' },
      { c: '🤏', n: '捏一点', k: '捏 小小 一点 一点点' },
      { c: '✌️', n: '胜利', k: '胜利 v 耶 peace' },
      { c: '🤞', n: '许愿', k: '许愿 祈愿 crossed 好运' },
      { c: '🤟', n: '我爱你', k: '爱你 love rock i love you' },
      { c: '🤘', n: '摇滚', k: '摇滚 rock 牛 metal' },
      { c: '🤙', n: '给我电话', k: '电话 call me shaka' },
      { c: '👈', n: '指向左', k: '左 指向 left 指左' },
      { c: '👉', n: '指向右', k: '右 指向 right 指右' },
      { c: '👆', n: '指向上', k: '上 指向 up 指上' },
      { c: '👇', n: '指向下', k: '下 指向 down 指下' },
      { c: '☝️', n: '一指', k: '一 指向 index 第一' },
      { c: '👍', n: '赞', k: '赞 good thumbs up 点赞' },
      { c: '👎', n: '踩', k: '踩 差 thumbs down 不行' },
      { c: '✊', n: '拳头', k: '拳头 fist 力量 加油' },
      { c: '👊', n: '出拳', k: '出拳 punch fist 打' },
      { c: '🤛', n: '左拳', k: '左拳 fist left 左' },
      { c: '🤜', n: '右拳', k: '右拳 fist right 右' },
      { c: '👏', n: '鼓掌', k: '鼓掌 拍手 clap 赞 好' },
      { c: '🙌', n: '举手', k: '举手 庆祝 raising 耶' },
      { c: '👐', n: '张开手', k: '张开手 open hands 拥抱' },
      { c: '🤲', n: '合掌', k: '合掌 palms 捧 祈祷' },
      { c: '🤝', n: '握手', k: '握手 handshake 合作 你好' },
      { c: '🙏', n: '感谢', k: '感谢 祈祷 pray 谢谢 拜托' },
      { c: '✍️', n: '写字', k: '写字 writing 写 笔' },
      { c: '💪', n: '肌肉', k: '肌肉 力量 强 muscle 强壮' },
      { c: '🦾', n: '机械臂', k: '机械臂 假肢 metal arm' },
      { c: '🦵', n: '腿', k: '腿 leg 腿部' },
      { c: '🦿', n: '机械腿', k: '机械腿 假腿 metal leg' },
      { c: '🦶', n: '脚', k: '脚 foot 脚丫' },
      { c: '👂', n: '耳朵', k: '耳朵 ear 听' },
      { c: '🦻', n: '戴助听器', k: '助听器 ear hearing 耳朵' },
      { c: '👃', n: '鼻子', k: '鼻子 nose 闻' },
      { c: '🧠', n: '大脑', k: '大脑 brain 脑 聪明' },
      { c: '🫀', n: '心脏', k: '心脏 心 heart anatomy' },
      { c: '🫁', n: '肺', k: '肺 lungs 呼吸' },
      { c: '🦷', n: '牙齿', k: '牙齿 tooth 牙' },
      { c: '👀', n: '眼睛', k: '眼睛 看 eyes 盯' },
      { c: '👁️', n: '一只眼', k: '眼睛 eye 看' },
      { c: '👅', n: '舌头', k: '舌头 tongue 舔' },
      { c: '👄', n: '嘴巴', k: '嘴巴 mouth 唇' },
      { c: '👶', n: '婴儿', k: '婴儿 baby 宝宝 娃娃' },
      { c: '🧒', n: '儿童', k: '儿童 child 小孩 孩子' },
      { c: '👦', n: '男孩', k: '男孩 boy 儿子' },
      { c: '👧', n: '女孩', k: '女孩 girl 女儿' },
      { c: '🧑', n: '成人', k: '成人 person 人' },
      { c: '👨', n: '男人', k: '男人 man 爸爸' },
      { c: '👩', n: '女人', k: '女人 woman 妈妈' },
      { c: '🧓', n: '老人', k: '老人 older 老爷爷 老奶奶' },
      { c: '👴', n: '老爷爷', k: '老爷爷 old man 爷爷' },
      { c: '👵', n: '老奶奶', k: '老奶奶 old woman 奶奶' },
      { c: '🙅', n: '不行', k: '不行 no 拒绝 gesture' },
      { c: '🙆', n: '好的', k: '好的 ok gesture 行' },
      { c: '💁', n: '指引', k: '指引 询问 tipping 信息' },
      { c: '🙋', n: '举手', k: '举手 raising hand 我 问题' },
      { c: '🙇', n: '鞠躬', k: '鞠躬 bow 道歉 感谢 拜' },
      { c: '🤦', n: '捂脸', k: '捂脸 face palm 无语 郁闷' },
      { c: '🤷', n: '耸肩', k: '耸肩 shrug 不知道 随便' },
      { c: '🧑‍⚕️', n: '医护', k: '医生 医护 health worker' },
      { c: '👨‍🍳', n: '男厨师', k: '厨师 男 cook 厨子' },
      { c: '👩‍🍳', n: '女厨师', k: '厨师 女 cook 厨子' },
      { c: '👨‍💻', n: '男程序员', k: '程序员 男 coder 技术' },
      { c: '👩‍💻', n: '女程序员', k: '程序员 女 coder 技术' },
      { c: '🧑‍🚀', n: '宇航员', k: '宇航员 astronaut 太空' },
      { c: '🦸', n: '超级英雄', k: '超级英雄 superhero 英雄' },
      { c: '🦹', n: '超级反派', k: '反派 supervillain 坏人' },
      { c: '🧙', n: '魔法师', k: '魔法师 mage 巫师 wizard' },
      { c: '🧚', n: '仙女', k: '仙女 fairy 小精灵' },
      { c: '🧛', n: '吸血鬼', k: '吸血鬼 vampire 德古拉' },
      { c: '🧜', n: '美人鱼', k: '美人鱼 mermaid 海' },
      { c: '🧝', n: '精灵', k: '精灵 elf 魔法' },
      { c: '🧞', n: '神灯精灵', k: '精灵 genie 神灯' },
      { c: '🧟', n: '僵尸', k: '僵尸 zombie 丧尸' },
      { c: '💆', n: '按摩', k: '按摩 massage 放松 舒服' },
      { c: '💇', n: '理发', k: '理发 剪发 haircut 发型' },
      { c: '🚶', n: '走路', k: '走路 walking 散步' },
      { c: '🏃', n: '跑步', k: '跑步 running 跑 锻炼' },
      { c: '💃', n: '跳舞女', k: '跳舞 女 dance 舞' },
      { c: '🕺', n: '跳舞男', k: '跳舞 男 dance 舞' },
      { c: '👯', n: '兔女郎', k: '兔女郎 双人 dance 派对' },
      { c: '🧗', n: '攀岩', k: '攀岩 climbing 爬山' },
      { c: '🤺', n: '击剑', k: '击剑 fencing 剑' },
      { c: '🏄', n: '冲浪', k: '冲浪 surfing 海浪' },
      { c: '🏊', n: '游泳', k: '游泳 swimming 游 泳' },
      { c: '🛀', n: '洗澡', k: '洗澡 bath 浴缸 泡澡' },
      { c: '🛌', n: '睡觉', k: '睡觉 sleep 床 睡觉' }
    ]
  },
  {
    id: 'animals', name: '动物自然', icon: '🐶',
    emojis: [
      { c: '🐶', n: '小狗', k: '小狗 dog 狗 汪' },
      { c: '🐱', n: '小猫', k: '小猫 cat 猫 喵' },
      { c: '🐭', n: '老鼠', k: '老鼠 mouse 鼠' },
      { c: '🐹', n: '仓鼠', k: '仓鼠 hamster 鼠' },
      { c: '🐰', n: '兔子', k: '兔子 rabbit 兔' },
      { c: '🦊', n: '狐狸', k: '狐狸 fox 狸' },
      { c: '🐻', n: '熊', k: '熊 bear 熊' },
      { c: '🐼', n: '熊猫', k: '熊猫 panda 国宝' },
      { c: '🐻‍❄️', n: '北极熊', k: '北极熊 polar bear' },
      { c: '🐨', n: '考拉', k: '考拉 koala 树袋熊' },
      { c: '🐯', n: '老虎', k: '老虎 tiger 虎' },
      { c: '🦁', n: '狮子', k: '狮子 lion 狮' },
      { c: '🐮', n: '牛', k: '牛 cow 牛' },
      { c: '🐷', n: '猪', k: '猪 pig 豚' },
      { c: '🐸', n: '青蛙', k: '青蛙 frog 蛙' },
      { c: '🐵', n: '猴子', k: '猴子 monkey face 猴' },
      { c: '🙈', n: '不看', k: '不看 hear no evil 蒙眼 猴' },
      { c: '🙉', n: '不听', k: '不听 see no evil 蒙耳 猴' },
      { c: '🙊', n: '不说', k: '不说 speak no evil 蒙嘴 猴' },
      { c: '🐒', n: '猴', k: '猴 monkey 猕猴' },
      { c: '🐔', n: '鸡', k: '鸡 chicken 鸡' },
      { c: '🐧', n: '企鹅', k: '企鹅 penguin' },
      { c: '🐦', n: '小鸟', k: '小鸟 bird 鸟' },
      { c: '🐤', n: '小鸡', k: '小鸡 baby chick 鸡' },
      { c: '🦆', n: '鸭子', k: '鸭子 duck 鸭' },
      { c: '🦅', n: '鹰', k: '鹰 eagle 雕' },
      { c: '🦉', n: '猫头鹰', k: '猫头鹰 owl 鸮' },
      { c: '🦇', n: '蝙蝠', k: '蝙蝠 bat' },
      { c: '🐺', n: '狼', k: '狼 wolf 豺' },
      { c: '🐗', n: '野猪', k: '野猪 boar 猪' },
      { c: '🐴', n: '马', k: '马 horse 马' },
      { c: '🦄', n: '独角兽', k: '独角兽 unicorn 神兽' },
      { c: '🐝', n: '蜜蜂', k: '蜜蜂 bee 蜂 蜜' },
      { c: '🐛', n: '虫子', k: '虫子 bug worm 虫' },
      { c: '🦋', n: '蝴蝶', k: '蝴蝶 butterfly 蝶' },
      { c: '🐌', n: '蜗牛', k: '蜗牛 snail' },
      { c: '🐞', n: '瓢虫', k: '瓢虫 ladybug 虫' },
      { c: '🐜', n: '蚂蚁', k: '蚂蚁 ant 蚁' },
      { c: '🦗', n: '蟋蟀', k: '蟋蟀 cricket 蝈蝈' },
      { c: '🕷️', n: '蜘蛛', k: '蜘蛛 spider 蛛' },
      { c: '🦂', n: '蝎子', k: '蝎子 scorpion 蝎' },
      { c: '🦟', n: '蚊子', k: '蚊子 mosquito 蚊' },
      { c: '🦠', n: '微生物', k: '微生物 bacteria 病菌' },
      { c: '🐢', n: '乌龟', k: '乌龟 turtle 龟' },
      { c: '🐍', n: '蛇', k: '蛇 snake 蛇' },
      { c: '🦎', n: '蜥蜴', k: '蜥蜴 lizard 蛇' },
      { c: '🦖', n: '霸王龙', k: '霸王龙 t-rex 恐龙' },
      { c: '🦕', n: '蜥脚龙', k: '蜥脚龙 sauropod 恐龙' },
      { c: '🐙', n: '章鱼', k: '章鱼 octopus 八爪鱼' },
      { c: '🦑', n: '鱿鱼', k: '鱿鱼 squid 墨鱼' },
      { c: '🦐', n: '虾', k: '虾 shrimp 虾' },
      { c: '🦞', n: '龙虾', k: '龙虾 lobster 龙虾' },
      { c: '🦀', n: '螃蟹', k: '螃蟹 crab 蟹' },
      { c: '🐡', n: '河豚', k: '河豚 blowfish 鱼' },
      { c: '🐠', n: '热带鱼', k: '热带鱼 fish 鱼' },
      { c: '🐟', n: '鱼', k: '鱼 fish 鱼' },
      { c: '🐬', n: '海豚', k: '海豚 dolphin 豚' },
      { c: '🐳', n: '鲸鱼', k: '鲸鱼 whale spout 鲸' },
      { c: '🐋', n: '鲸', k: '鲸 whale 鲸' },
      { c: '🦈', n: '鲨鱼', k: '鲨鱼 shark 鲨' },
      { c: '🐊', n: '鳄鱼', k: '鳄鱼 crocodile 鳄' },
      { c: '🦓', n: '斑马', k: '斑马 zebra 马' },
      { c: '🦍', n: '大猩猩', k: '大猩猩 gorilla 猿' },
      { c: '🐘', n: '大象', k: '大象 elephant 象' },
      { c: '🦛', n: '河马', k: '河马 hippo 河马' },
      { c: '🦏', n: '犀牛', k: '犀牛 rhino 犀' },
      { c: '🐪', n: '骆驼', k: '骆驼 camel 驼' },
      { c: '🦒', n: '长颈鹿', k: '长颈鹿 giraffe 鹿' },
      { c: '🦘', n: '袋鼠', k: '袋鼠 kangaroo 鼠' },
      { c: '🐄', n: '奶牛', k: '奶牛 cow 牛 奶' },
      { c: '🐎', n: '马', k: '马 horse 骏马' },
      { c: '🐖', n: '猪', k: '猪 pig 豚' },
      { c: '🐑', n: '绵羊', k: '绵羊 sheep 羊' },
      { c: '🐐', n: '山羊', k: '山羊 goat 羊' },
      { c: '🦌', n: '鹿', k: '鹿 deer 鹿' },
      { c: '🐕', n: '狗', k: '狗 dog 犬' },
      { c: '🐩', n: '贵宾犬', k: '贵宾犬 poodle 狗' },
      { c: '🐈', n: '猫', k: '猫 cat 猫' },
      { c: '🐓', n: '公鸡', k: '公鸡 rooster 鸡' },
      { c: '🦃', n: '火鸡', k: '火鸡 turkey 鸡' },
      { c: '🕊️', n: '鸽子', k: '鸽子 dove 和平 鸟' },
      { c: '🐉', n: '龙', k: '龙 dragon 神兽' },
      { c: '🐲', n: '龙头', k: '龙头 dragon 龙' },
      { c: '🌵', n: '仙人掌', k: '仙人掌 cactus 植物' },
      { c: '🎄', n: '圣诞树', k: '圣诞树 christmas 圣诞' },
      { c: '🌲', n: '松树', k: '松树 evergreen tree 树' },
      { c: '🌳', n: '落叶树', k: '落叶树 tree 树' },
      { c: '🌴', n: '椰子树', k: '椰子树 palm 棕榈' },
      { c: '🌱', n: '幼苗', k: '幼苗 sprout 植物' },
      { c: '🌿', n: '草药', k: '草药 herb 草' },
      { c: '☘️', n: '三叶草', k: '三叶草 shamrock 幸运' },
      { c: '🍀', n: '四叶草', k: '四叶草 clover 幸运' },
      { c: '🍁', n: '枫叶', k: '枫叶 maple 秋天' },
      { c: '🍂', n: '落叶', k: '落叶 fallen leaf 秋' },
      { c: '🍃', n: '吹叶', k: '吹叶 wind leaf 风' },
      { c: '🌺', n: '木槿花', k: '木槿花 hibiscus 花' },
      { c: '🌸', n: '樱花', k: '樱花 blossom 花 春' },
      { c: '🌼', n: '雏菊', k: '雏菊 daisy 花' },
      { c: '🌷', n: '郁金香', k: '郁金香 tulip 花' },
      { c: '🌹', n: '玫瑰', k: '玫瑰 rose 花 爱' },
      { c: '🌻', n: '向日葵', k: '向日葵 sunflower 花 阳' },
      { c: '💐', n: '花束', k: '花束 bouquet 花' },
      { c: '🍄', n: '蘑菇', k: '蘑菇 mushroom 菌' },
      { c: '🌍', n: '地球', k: '地球 earth globe 世界' },
      { c: '🌎', n: '美洲地球', k: '地球 earth 美洲' },
      { c: '🌏', n: '亚澳地球', k: '地球 earth 亚洲' },
      { c: '🌕', n: '满月', k: '满月 full moon 月' },
      { c: '🌙', n: '弯月', k: '弯月 crescent 月' },
      { c: '⭐', n: '星星', k: '星星 star 星' },
      { c: '🌟', n: '闪星', k: '闪星 glowing star 亮' },
      { c: '✨', n: '闪烁', k: '闪烁 sparkle 闪 亮' },
      { c: '⚡', n: '闪电', k: '闪电 lightning 电 雷' },
      { c: '🔥', n: '火', k: '火 fire 燃 热门' },
      { c: '💧', n: '水滴', k: '水滴 droplet 水' },
      { c: '❄️', n: '雪花', k: '雪花 snowflake 雪 冷' },
      { c: '🌈', n: '彩虹', k: '彩虹 rainbow 雨' },
      { c: '☀️', n: '太阳', k: '太阳 sun 晴' },
      { c: '⛅', n: '多云', k: '多云 cloud sun 天气' },
      { c: '☁️', n: '云', k: '云 cloud 天气' },
      { c: '🌧️', n: '下雨', k: '下雨 rain cloud 雨' },
      { c: '⛈️', n: '雷雨', k: '雷雨 thunder storm 雨' },
      { c: '🌨️', n: '下雪', k: '下雪 snow cloud 雪' },
      { c: '🌪️', n: '龙卷风', k: '龙卷风 tornado 风' },
      { c: '🌊', n: '海浪', k: '海浪 wave 水 海' }
    ]
  },
  {
    id: 'food', name: '食物饮品', icon: '🍔',
    emojis: [
      { c: '🍏', n: '青苹果', k: '青苹果 green apple 苹果' },
      { c: '🍎', n: '红苹果', k: '红苹果 apple 苹果' },
      { c: '🍐', n: '梨', k: '梨 pear' },
      { c: '🍊', n: '橘子', k: '橘子 tangerine 橙' },
      { c: '🍋', n: '柠檬', k: '柠檬 lemon 柠' },
      { c: '🍌', n: '香蕉', k: '香蕉 banana 蕉' },
      { c: '🍉', n: '西瓜', k: '西瓜 watermelon 瓜' },
      { c: '🍇', n: '葡萄', k: '葡萄 grapes 葡' },
      { c: '🍓', n: '草莓', k: '草莓 strawberry 莓' },
      { c: '🫐', n: '蓝莓', k: '蓝莓 blueberries 莓' },
      { c: '🍈', n: '哈密瓜', k: '哈密瓜 melon 瓜' },
      { c: '🍒', n: '樱桃', k: '樱桃 cherries 樱' },
      { c: '🍑', n: '桃子', k: '桃子 peach 桃' },
      { c: '🥭', n: '芒果', k: '芒果 mango 芒' },
      { c: '🍍', n: '菠萝', k: '菠萝 pineapple 菠萝' },
      { c: '🥥', n: '椰子', k: '椰子 coconut 椰' },
      { c: '🥝', n: '猕猴桃', k: '猕猴桃 kiwi 奇异果' },
      { c: '🍅', n: '番茄', k: '番茄 tomato 西红柿' },
      { c: '🍆', n: '茄子', k: '茄子 eggplant 茄' },
      { c: '🥑', n: '牛油果', k: '牛油果 avocado 鳄梨' },
      { c: '🥦', n: '西兰花', k: '西兰花 broccoli 花' },
      { c: '🥬', n: '生菜', k: '生菜 lettuce 蔬菜' },
      { c: '🥒', n: '黄瓜', k: '黄瓜 cucumber 瓜' },
      { c: '🌶️', n: '辣椒', k: '辣椒 hot pepper 辣' },
      { c: '🌽', n: '玉米', k: '玉米 corn 玉米' },
      { c: '🥕', n: '胡萝卜', k: '胡萝卜 carrot 萝卜' },
      { c: '🧄', n: '大蒜', k: '大蒜 garlic 蒜' },
      { c: '🧅', n: '洋葱', k: '洋葱 onion 葱' },
      { c: '🥔', n: '土豆', k: '土豆 potato 马铃薯' },
      { c: '🍠', n: '烤地瓜', k: '烤地瓜 sweet potato 红薯' },
      { c: '🥐', n: '牛角包', k: '牛角包 croissant 可颂' },
      { c: '🥯', n: '贝果', k: '贝果 bagel 面包' },
      { c: '🍞', n: '面包', k: '面包 bread 面包' },
      { c: '🥖', n: '法棍', k: '法棍 baguette 面包' },
      { c: '🧀', n: '奶酪', k: '奶酪 cheese 芝士' },
      { c: '🥚', n: '鸡蛋', k: '鸡蛋 egg 蛋' },
      { c: '🍳', n: '煎蛋', k: '煎蛋 fried egg 炒蛋' },
      { c: '🧈', n: '黄油', k: '黄油 butter 黄油' },
      { c: '🥞', n: '松饼', k: '松饼 pancakes 煎饼' },
      { c: '🧇', n: '华夫饼', k: '华夫饼 waffle 华夫' },
      { c: '🥓', n: '培根', k: '培根 bacon 肉' },
      { c: '🥩', n: '牛排', k: '牛排 steak 肉' },
      { c: '🍗', n: '鸡腿', k: '鸡腿 chicken leg 鸡' },
      { c: '🍖', n: '骨头肉', k: '骨头肉 meat bone 肉' },
      { c: '🌭', n: '热狗', k: '热狗 hotdog 火腿肠' },
      { c: '🍔', n: '汉堡', k: '汉堡 burger 汉堡包' },
      { c: '🍟', n: '薯条', k: '薯条 fries 薯' },
      { c: '🍕', n: '披萨', k: '披萨 pizza 必胜客' },
      { c: '🥪', n: '三明治', k: '三明治 sandwich' },
      { c: '🌮', n: '玉米卷', k: '玉米卷 taco 墨西哥' },
      { c: '🌯', n: '卷饼', k: '卷饼 burrito 墨西哥' },
      { c: '🥙', n: '皮塔饼', k: '皮塔饼 pita 卷' },
      { c: '🧆', n: '法拉费', k: '法拉费 falafel 鹰嘴豆' },
      { c: '🍣', n: '寿司', k: '寿司 sushi 日料' },
      { c: '🍱', n: '便当', k: '便当 bento box 日料' },
      { c: '🍙', n: '饭团', k: '饭团 rice ball 日料' },
      { c: '🍚', n: '米饭', k: '米饭 rice 饭' },
      { c: '🍜', n: '拉面', k: '拉面 ramen 面条 面' },
      { c: '🍝', n: '意面', k: '意面 spaghetti 面条' },
      { c: '🍲', n: '火锅', k: '火锅 pot of food 汤' },
      { c: '🍛', n: '咖喱', k: '咖喱 curry 咖喱' },
      { c: '🥟', n: '饺子', k: '饺子 dumpling 馄饨' },
      { c: '🍤', n: '炸虾', k: '炸虾 fried shrimp 虾 天妇罗' },
      { c: '🍢', n: '关东煮', k: '关东煮 oden 串' },
      { c: '🍥', n: '鱼板', k: '鱼板 fish cake 糕' },
      { c: '🥮', n: '月饼', k: '月饼 moon cake 中秋' },
      { c: '🍡', n: '团子', k: '团子 dango 串' },
      { c: '🍧', n: '刨冰', k: '刨冰 shaved ice 冰' },
      { c: '🍨', n: '冰淇淋', k: '冰淇淋 ice cream 冰激凌' },
      { c: '🍦', n: '甜筒', k: '甜筒 ice cream 冰激凌' },
      { c: '🥧', n: '派', k: '派 pie 派' },
      { c: '🍫', n: '巧克力', k: '巧克力 chocolate 巧克力' },
      { c: '🍬', n: '糖果', k: '糖果 candy 糖' },
      { c: '🍭', n: '棒棒糖', k: '棒棒糖 lollipop 糖' },
      { c: '🍮', n: '布丁', k: '布丁 pudding 甜' },
      { c: '🍯', n: '蜂蜜', k: '蜂蜜 honey 蜜' },
      { c: '🍼', n: '奶瓶', k: '奶瓶 baby bottle 奶' },
      { c: '🥛', n: '牛奶', k: '牛奶 milk glass 奶' },
      { c: '☕', n: '咖啡', k: '咖啡 coffee 咖啡' },
      { c: '🍵', n: '茶', k: '茶 tea 绿茶' },
      { c: '🧃', n: '果汁盒', k: '果汁盒 juice box 饮料' },
      { c: '🥤', n: '冷饮', k: '冷饮 cup straw 饮料' },
      { c: '🧋', n: '珍珠奶茶', k: '珍珠奶茶 bubble tea 奶茶' },
      { c: '🍶', n: '清酒', k: '清酒 sake 酒' },
      { c: '🍺', n: '啤酒', k: '啤酒 beer 啤酒' },
      { c: '🍻', n: '干杯', k: '干杯 cheers 啤酒 碰杯' },
      { c: '🥂', n: '碰杯', k: '碰杯 clink 祝酒' },
      { c: '🍷', n: '红酒', k: '红酒 wine 葡萄酒' },
      { c: '🥃', n: '威士忌', k: '威士忌 whisky 烈酒' },
      { c: '🍸', n: '鸡尾酒', k: '鸡尾酒 cocktail martini' },
      { c: '🍹', n: '热带饮料', k: '热带饮料 tropical 鸡尾酒' },
      { c: '🥢', n: '筷子', k: '筷子 chopsticks 餐具' },
      { c: '🍽️', n: '刀叉盘', k: '刀叉盘 fork plate 餐具' },
      { c: '🍴', n: '刀叉', k: '刀叉 fork knife 餐具' },
      { c: '🥄', n: '勺子', k: '勺子 spoon 餐具' }
    ]
  }
];

// 合并额外分类（活动/旅行/物品/符号/旗帜）
const { EXTRA_CATEGORIES } = require('./emoji-data-extra');
const ALL_CATEGORIES = EMOJI_CATEGORIES.concat(EXTRA_CATEGORIES);

// 获取所有分类（含颜文字与特殊符号）
function getAllCategories() {
  const { KAO_DATA, SYMBOLS_DATA } = require('./emoji-data-kao');
  return ALL_CATEGORIES.concat([
    { id: 'kao', name: '颜文字', icon: 'ʕ•ᴥ•ʔ', emojis: KAO_DATA },
    { id: 'special', name: '特殊符号', icon: '★', emojis: SYMBOLS_DATA }
  ]);
}

// 获取所有 emoji 扁平数组
function getAllEmojis() {
  return getAllCategories().flatMap(cat => cat.emojis.map(e => ({ ...e, cat: cat.id, catName: cat.name })));
}

module.exports = { EMOJI_CATEGORIES, ALL_CATEGORIES, getAllCategories, getAllEmojis };
